yunionio/sqlchemy

query.go

mark query.Count as deprecated

fix: mark query.Count as deprecated

---

main_test.go
query.go
query_test.go

当查询中有GROUP BY语句时，当前的Count实现不能表达出整体SQuery的结果数
需要更新依赖方的vendor
/cc @swordqiu 
/cc @bistuzx

query: 改正Count调用

---

query.go

query: log not found fields only when DEBUG_SQLCHEMY
/cc @yunionio/maintainer

query: log not found fields only when DEBUG_SQLCHEMY

---

insert.go

fix: allow text primary key with empty string

---

update.go

当update没有更新row时，返回sql.ErrNoRows

fix: update no rows returnes sql.ErrNoRows

---

query.go

在执行squery的时候，会忽略having子句，修复了这个问题

Fix: ignore having clause when squery rows

---

inc.go
sqltest/main.go

新增：Increment/Decrement方法允许对数字型的字段进行+=和-=的原子更新操作
type Table {
Id string
Age int
}
// data: Table{Id:"123", Age:10}
diff := Table{Id: "123", Age: 1}
table.Increment(diff, result)
// result: Table{id:"123", Age: 11}
/cc @yousong @wanyaoqi @zexi

add: support incremental add/sub for numeric fields

---

column.go
const.go
insert.go

增加一个allow_zero的列tag，表示该列在insert/insert_or_update时候，允许插入zero值。例如，一个column为数字，default为-1。alllow_zero=true, 则允许插入一个0值。如果allow_zero=false，则该列无法插入0值（因为0为zero，insert认为该列未初始化，所以不插入）。
/cc @yousong @zexi @wanyaoqi @rainzm

feature: add new tag allow_zero, whichi allow insert or update zero value

---

column.go

修正：非nil的JSONObject不应该序列化为空字符串，例如JSONBool{false}应该是false，而不是""
/cc @yousong @zexi @wanyaoqi

fix: non-nil jsonobject should not be saved as empty string

---

sync.go

修正：对比table schema时，忽略了primary key属性的比较
/cc @zexi @yousong @wanyaoqi

fix: schema sync ignore primary key changes

---

column.go
sync.go

修正：目前默认保留remove的column，但是一些column是no-nullable并且无default，在给这样的表插入数据时，Maraiadb 10.3会报错。因此需要把这些column的no-nullable属性去掉。
/cc @yousong @zexi @wanyaoqi

fix: drop no-nullable attributes for no-default deleted columns

---

query.go
table.go

为query增加了Snapshot和IsAltered两个方法，用来判断一个query是否在子函数中被改变
使用示例：
netQ := NetworkManager.Query("id").Snapshot()
netQ, err := manager.SWireResourceBaseManager.ListItemFilter(ctx, netQ, userCred, query.WireFilterListInput)
if err != nil {
return nil, errors.Wrap(err, "SWireResourceBaseManager.ListItemFilter")
}
if netQ.IsAltered() {
q = q.Filter(sqlchemy.In(q.Field("network_id"), netQ.SubQuery()))
}

feature: add query snapshot feature, so as to know whether the query is altered

---

query.go

fix: subquery field names should be quoted

---

update.go

1. 删除的代码块：
```go
if !gotypes.IsNil(of) {
if c.IsPrimary() && !c.IsZero(of) { // skip update primary key
primaries[k] = of
continue
}
}
```
与上面的代码块：
```go
if c.IsPrimary() {
if !gotypes.IsNil(of) && !c.IsZero(of) {
primaries[k] = of
} else if c.IsText() {
primaries[k] = ""
} else {
return nil, ErrEmptyPrimaryKey
}
continue
}
```
的第一处 if 的逻辑重复了，并且删除的代码块是不会执行的。
2. primaries 里面的 value 会作为 where 的判断，并且在下面的
```go
q := us.tableSpec.Query()
for k, v := range primaries {
q = q.Equals(k, v)
}
err = q.First(dt)
if err != nil {
return nil, errors.Wrap(err, "query after update failed")
}
```
也用到了，所以 value 需要做一层 column.ConvertFromValue 的转换。

fix: Convert primary column's value when saveUpdate

---

conditions.go

```
conditions: use "0" const in place of empty IN condition
```
/cc @swordqiu @zexi

conditions: use "0" in place of empty IN condition

---

query.go

This is to ensure that the results of multiple calls to SSubQuery.Expression
must be the same without changing SSubQuery.
And SQuery.Snapshot and SQuery.Altered() can work fine.

fix: make sure the order of fields in SSubQuery

---

column.go
sync.go
table.go

mysql utf8使用utf8mb4。参考 https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4.
因为转为utf8mb4，导致ut8 varchar primary key的最大长度不能超过191（因为最大primary key byte长度为767, 767/4=191）。所以这个修改之后，长度超过191的相应的mysql model的utf8 primary varchar定义需要修改。

fix: mysql utf8 should use utf8mb4:

---

insert.go

如果不支持InsertOrUpdate操作，则执行insert操作

fix: fall back to insert if insertOrUpdate not supported

---

backends.go
backends/clickhouse/clickhouse.go
backends/mysql/mysql.go
backends/mysql/parse.go
backends/mysql/parse_test.go
backends/mysql/query_test.go
backends/sqlite/parse.go
backends/sqlite/parse_test.go
backends/sqlite/sqlite.go
backends_base.go
constraint_test.go
index.go
query_test.go
sync_test.go
table.go
union.go

修正：1. Union需要跟backend相关 2. splitable的子表的索引名字重复

fix: 1. backend-specific union operator 2. splitable index

---

reflect.go
sql.go

修正：clickhouse参数不准的错误，规避clickhouse-go的bug
INSERT INTO `tags_tbl` (`account_id`, `batch_id`, `created_at`, `day`, `deleted`, `id`, `key`, `mark`, `resource_id`, `resource_project_id`, `update_version`, `updated_at`, `value`) VALUES (?, ?, NOW('UTC'), ?, ?, ?, ?, ?, ?, ?, ?, NOW('UTC'), ?)
values: []interface {}{"", "", 0, 0x0, "a6a46d60-fa5e-41f8-88df-44f931e63d22", "user:Owner", "", "c99aaf82-4b40-497d-83ca-f2695d46af2c", "", 0, "zeno"}
[Append]: expected 13 arguments, got 11

fix: clickhouse argument count error

---

backends/clickhouse/clickhouse.go
backends/clickhouse/column.go
backends/clickhouse/column_test.go
backends/clickhouse/columninfo.go
go.mod

clickhouse datetime column specify utc timezone by default

fix: clickhouse datetime column specify utc timezone by default

---

backends/dameng/column.go
backends/dameng/column_test.go

fix: dameng timestamp default precision zero

fix: dameng timestamp default precision zero

---

column.go
insert.go
insert_batch.go
update.go

fix: truncate string variables for varchar fields

fix: truncate string variables for varchar fields

---

backends/clickhouse/column.go
backends/clickhouse/column_test.go
backends/clickhouse/sync.go
backends/dameng/column.go
backends/dameng/column_test.go
backends/dameng/dameng.go
backends/mysql/column.go
backends/mysql/column_test.go
backends/sqlite/column.go
conditions.go
functions.go
querydefs.go
queryfield.go
rawquery.go
reflect.go
subquery.go
table.go
union.go

fix: IQueryField support ConvertFromValue

fix: IQueryField support ConvertFromValue
