debug.go

Configurable debug option

---

query.go
sqltest/main.go
union.go

feature: support SQL UNION DISTINCT operation

---

query.go
sqltest/main.go

fix: query.Count returns not only count but also error

---

insert.go

支持insert时初始化created_at及updated_at时间

支持insert时初始化created_at及updated_at时间

---

update.go

调整updatediff的输出格式
/cc @Zexi @yousong

fix: refine the output of update diffs

---

column.go
debug.go
errors.go
insert.go
insert_test.go
sqltest/main.go
sync.go
union.go

1. support InsertOrUpdate operation 
2. union recode
3. force convert enum into text fields.
4. support date or timestamp fields

feature: support InsertOrUpdate operation etc. misc.

---

column.go
conditions.go
conditions_test.go
const.go
constraint.go
constraint_test.go
debug.go
doc.go
errors.go
field_update.go
filter.go
functions.go
index.go
insert.go
insert_test.go
parser.go
query.go
rawquery.go
reflect.go
sql.go
sqltest/main.go
sync.go
sync_test.go
table.go
tablealias.go
union.go
update.go

CREATE TABLE的table name应该quote

fix: table name should be quoted in create table statement

---

functions.go

query支持字符串变量 NewStringField("const").Label("name")

fix: support query string constant

---

README.md
conditions.go
const.go
debug.go
fetch.go
functions.go
query.go
sqltest/main.go
table.go

改进：
1、在子查询中，只查询需要的字段，不再需要查询所有字段 
2. 增加fetch接口

optimization: 1. select subset of fields in subquery 2. add fetch method

---

table.go

table: 去掉不紧要log
/cc @yunionio/maintainer

table: 去掉不紧要log

---

query.go

移除order by必选是表字段限制
/cc @swordqiu

remove order by restrict

---

errors.go
update.go

update support empty primary string

---

insert.go
query.go
update.go

missing white space in insertOrupdate sql

fix: missing white space in insertOrupdate sql

---

update.go

fix: update debug log should show vars

---

update.go

fix: update model after update

---

functions.go

add replace function

---

functions.go

- support or and
- support field no alias
- support substr
/cc @swordqiu

feature: sql functions extend

---

column.go
column_test.go

避免潜在bug
/cc @yunionio/maintainer

将non-pointer boolean column default true的情况由warning改为panic

---

insert.go

修复默认为空的字符串没有被插入的问题
/cc @swordqiu

fix: text column empty string default insert

---

errors.go
fetch.go
field_update.go
insert.go
query.go
reflect.go
update.go

fix: error handling recode to conform with error process standard

---

README.md
errors.go
sync.go

1. 改进README.md
2. 隐藏TableNotExists的错误日志

fix: add examples into readme & hide TableNotExists error

---

sync.go

```
sync: log sql with closing semicolon
```
/cc @swordqiu

sync: log sql with closing semicolon

---

column.go
column_test.go

column: panic when text column intend to have a default
/cc @swordqiu

column: panic when text column intend to have a default

---

sync.go

修正：对于drop的column，需要去掉auto_increment的属性
/cc @yousong

fix: dropped column should drop auto_increment attribute

---

functions.go

* 新增INET_ATON function
/cc @swordqiu

add function inet aton

---

column.go
conditions.go
parser.go
reflect.go
table.go

1.  autoincrement可以指定开始的初始值
2. 支持alias type的column， e.g. type TCurrency string
3. 支持NoLaterThan和NoEarlierThan方法

feature&fixes: 1. autoincrement column initial offset 2. support alias type 3. support NoLaterThan and NoEarlierThan function

---

functions.go

feature: add TimestampAdd function

---

case.go
field_update.go
functions.go
query.go

增加：支持mysql case when ... then ... else end 方法

feature: support mysql case function

---

inc.go

increment/decreate增量操作使用输入的target的主键值进行查找

fix: increament/decreament update use target primary key

---

conditions.go

feature: add containsAny condition

---

sqltest/main.go

Ref: https://github.com/yunionio/sqlchemy/issues/61
/cc @zexi @swordqiu

sqltest: make it run again

---

sync.go
union.go

修正：remove log.Fatalf, as suggested in issue #64 
/cc @yousong @zexi

fix: remove fatalf logs, as suggested in issue #64

---

update.go

Make UpdateDiffs stringer return JSON string

---

.circleci/config.yml
conditions.go
filter.go

```
Add true, false condition
```
/cc @zexi @ioito @wanyaoqi @swordqiu

Add true, false condition

---

functions.go
query.go
sql.go
sync.go
table.go

feature: abstract tablespec interface, for split table

---

column.go

改进：Column增加SetDefault方法，允许动态更改column的缺省值

feature: allow set column default value

---

union.go

修正：union空的query时panic
/cc @zexi

fix: panic if union empty query

---

README.md

add badge of circleci and goreportcard to README.md

feature: add go report card etc. to README.md

---

field_update.go
insert.go
update.go

fix: update with no affected

---

insert.go

fix: before insert

---

parser.go

fix: more info for panic

---

query_test.go
table.go
union.go

fix: union query missing alais in expression

fix: union missing expression alias

---

debug.go
query.go

optimized: sql debug format

---

column.go
conditions.go
debug.go
errors.go
fetch.go
filter.go
functions.go
inc.go
index.go
insert.go
parser.go
query.go
reflect.go
sqltest/main.go
sync.go
table.go
tablealias.go
union.go

fix: golint fixes

---

column.go
filter.go
functions.go
inc.go
sync.go
table.go

fix: misspell errors

---

README.md

fix: add codecov badget to README

---

README.md

Golang syntax highlighting

---

backends/clickhouse/clickhouse.go
backends/mysql/const.go
backends/mysql/insert_test.go
backends/mysql/mysql.go
backends/sqlite/column.go
backends/sqlite/column_test.go
backends/sqlite/sqlite.go
constraint.go
constraint_test.go
debug_test.go
field_update.go
field_update_test.go
inc.go
index.go
insert.go
insert_test.go
sql.go
update.go
update_test.go

fix: bugfixes

---

backends_mock.go
field_update_test.go
inc_test.go
insert_test.go
query_test.go
sync_test.go
update_test.go

fix: export SetupMockDB

---

README.md

fix: fix typos in README.md

---

functions.go
query_test.go

fix: stringfield and constfield expression

---

backends/clickhouse/column.go
backends/mysql/column.go
backends/sqlite/column.go
column.go
column_test.go

fail to serialize CompoundColumn

fix: fail to serialize CompoundColumn

---

README.md
backends/mysql/query_test.go
query_test.go
union.go

fix: union syntax error

---

sql.go

fix(sqlchemy): sDBReferer add return DBName func

---

functions.go
query_test.go

fix: should use reference in expression of function

---

backends.go
backends/clickhouse/sync.go
backends/clickhouse/sync_test.go
backends/mysql/sync.go
backends/mysql/sync_test.go
backends/sqlite/sync.go
backends/sqlite/sync_test.go
backends_mock.go
index.go
sync.go
sync_test.go

fix: sync table recode

---

backends/mysql/sync.go
backends/sqlite/sync.go
reflect.go
reflect_test.go
sync.go

fix: set value of sql string not support any general types

---

backends/sqlite/sync.go
backends/sqlite/sync_test.go
reflect.go
reflect_test.go

fix: set value from sql string error for boolean

---

reflect_test.go

fix: set value from sql string test

---

reflect.go

fix: reset slice/map before set value of a slice/map column

---

backends/clickhouse/clickhouse.go
backends/clickhouse/column.go
backends/clickhouse/column_test.go
backends/clickhouse/columninfo.go
backends/clickhouse/columninfo_test.go
backends/clickhouse/consts.go
backends/clickhouse/sync.go
backends/clickhouse/sync_test.go
backends/clickhouse/ttl.go
backends/clickhouse/ttl_test.go
sync.go
sync_test.go

feature: clickhouse ttl support

---

backends/clickhouse/columninfo.go

fix: clickhouse string default value should remove quota

---

backends/mysql/column.go

fix: mysql tristate backward compatible

---

backends_mock.go
update.go
update_test.go

fix: update text primary key

---

update.go

fix: allow update text primary key

---

backends/clickhouse/sync.go
backends/mysql/sync.go
backends/sqlite/sync.go
sync.go

fix: alter sql debug

---

sync.go

fix: alter log

---

.circleci/config.yml

fix: update circlecir config

---

backends/mysql/column.go

fix: show colume name with warn

---

field_update.go
inc.go
parser.go
update.go

1. Columns() may cause duplicate column name
2. keep order of fields for update SQL

fix: columns race conditon cause duplicate column name

---

update.go

preserve UpdateDiffs definition

---

backends_mock.go
insert.go
insert_test.go

fix: insertOrUpdate updates empty fields

---

backends/mysql/mysql.go
backends/mysql/sync.go
backends/sqlite/sqlite.go
backends/sqlite/sync.go
table.go

fix: sync table should sync indexes

---

functions.go

fix: add bc function

---

functions.go

feat: add bc function

---

update.go

update时，只有新旧value的json string不同才更新column

fix: update column when json string of the value changed

---

backends/mysql/query_test.go
functions.go
query_test.go
union.go

add functions of upper, lower, group_concat2

feature: add lower, upper, group_concat2

---

backends.go
backends/clickhouse/clickhouse.go
backends/clickhouse/functions.go
backends/mysql/functions.go
backends/sqlite/functions.go
backends_base.go
case.go
conditions.go
conditions_test.go
errors.go
functions.go
query.go
query_test.go
querydefs.go
rawquery.go
subquery.go
table.go
union.go

backend support of function and condition expression

feature: backend support of function and condition expression

---

backends/clickhouse/sync.go

fix: clickhouse do not sync primary keys

---

backends/clickhouse/functions.go

fix: clickhouse group_concat2 typo

---

backends.go
backends/clickhouse/clickhouse.go
backends/clickhouse/update_test.go
backends/mysql/mysql.go
backends/sqlite/sqlite.go
backends_base.go
backends_mock.go
conditions.go
field_update.go
field_update_test.go
inc.go
inc_test.go
insert.go
insert_test.go
update.go
update_test.go

backend 支持获取当前时间函数（UTC or locatime）

fix: backend support timestamp string(utc or localtime)

---

filter.go
query.go
querydefs.go

fix: remove having clause

---

backends/clickhouse/column.go
sql.go

fix: clickhouse ignore primary tag

---

.circleci/config.yml
go.mod
go.sum

upgrade clickhosue-go to v2.1.0

fix: upgrade clickhouse-go to v2.1.0

---

reflect.go

fix: get string value type check

---

sql.go

fix: clickhouse v1 insert should be in batch mode

fix: clickhouse v1 insert should be in batch mode

---

backends.go
backends/clickhouse/clickhouse.go
backends_base.go
insert.go

fix: support insert mixed vars

fix: support insert mixed vars

---

functions.go
query_test.go
reflect.go
reflect_test.go

use single quote instead of double quote to quote constant

fix: use single quote instead of double quote

---

backends.go
backends_base.go
sync.go
table.go

feature: table drop

---

query.go

fix: allow query reset fields

---

table.go

fix: table add sync interface method

fix: table add sync interface method

---

query.go

fix: avoid append duplicate columns

fix: avoid append duplicate columns

---

backends/clickhouse/clickhouse.go
backends/clickhouse/column.go
backends/clickhouse/columninfo.go
backends/clickhouse/columninfo_test.go
backends/clickhouse/sync.go
backends/sqlite/sync_test.go
column.go
column_test.go
query.go
subquery.go
sync.go
table.go

fix: support sync partitions of clickhosue

fix: support sync partitions of clickhosue

---

backends/clickhouse/clickhouse.go
backends/clickhouse/columninfo.go
backends/clickhouse/sync.go

fix: clickhouse sync full table if column in partition is nullable

---

backends/clickhouse/clickhouse.go
backends/clickhouse/column.go
backends/clickhouse/column_test.go
backends/mysql/column.go
backends/mysql/column_test.go
backends/mysql/mysql.go
backends/sqlite/column.go
backends/sqlite/column_test.go
backends/sqlite/sqlite.go

fix: show tristate nullable table name

---

reflect.go

fix: reflect json null failure

fix: reflect json null failure

---

delete_batch.go
update_batch.go

fix: add update_batch and delete_batch

fix: add update_batch and delete_batch

---

index.go

fix: create index with order

---

backends/mysql/sync.go
backends/sqlite/sync.go
index.go
sync_test.go

fix: drop raw index

---

backends/mysql/parse.go
backends/mysql/parse_test.go
backends/mysql/sync.go
backends/sqlite/parse.go
backends/sqlite/parse_test.go
backends/sqlite/sync.go
constraint_test.go
index.go
sync_test.go

fix: keep name of index when parse indexes

fix: keep name of index when parse indexes

---

backends/mysql/sync.go

fix: sync change primary of mysql

fix: sync change primary of mysql

---

backends/mysql/sync.go

Revert "fix: sync change primary of mysql"

---

backends.go
backends_base.go
functions.go

fix: support date_format func

---

query.go

fix: add copy for sql

---

.circleci/config.yml
.github/workflows/codecov.yml
backends.go
backends_base.go
conditions.go
conditions_test.go
const.go

feat: support REGEXP filter

---

backends.go
backends/clickhouse/clickhouse.go
backends/clickhouse/query_test.go
backends/mysql/query_test.go
backends/tests/helper.go
backends_base.go
conditions.go
conditions_test.go
filter.go

支持 clickhouse regexp 过滤，添加更多测试

fix: support clickhouse REGEXP filter

---

backends/mysql/sync.go

fix: mysql drop primary should be executed if change happens to primary keys

---

backends/mysql/column.go

fix: mysql set bool pointer column failed

---

backends/clickhouse/columninfo.go

fix(clickhouse): avoid panic

---

reflect.go

fix: unmaral map and array fixes

fix: unmaral map and array fixes

---

conditions.go
querydefs.go

fix: support noop condition

---

functions.go

fix: add abs function

---

ascii.go
conditions.go

fix: ensure comparison charset match

fix: ensure comparison charset match

---

backends/clickhouse/sync.go
backends/mysql/sync.go
backends/sqlite/sync.go
backends/sqlite/sync_test.go
column.go
const.go
query.go
sync.go
table.go

fix: support column rename

---

backends/clickhouse/query_test.go
backends/mysql/query_test.go
case.go
debug.go
query.go
query_test.go
querydefs.go
queryfield.go
subquery.go
table.go
union.go
update.go

fix: to ease query clickhouse, add query temp field, automatically add field alias

fix: to ease query clickhouse, add query temp field, automatically add field alias

---

update.go

fix: remove update SQL log

---

backends/clickhouse/column.go
backends/dameng/README.md
backends/dameng/column.go
backends/dameng/column_test.go
backends/dameng/sync.go
backends/mysql/column.go
backends/sqlite/column.go

fix: dameng should have no default for datetime column

fix: dameng should have no default for datetime column

---

functions.go

fix: avoid a large number of debug logs

---

backends/clickhouse/query_test.go
backends/dameng/functions.go
backends/dameng/query_test.go
backends/mysql/query_test.go
backends/tests/helper.go
functions.go
query_test.go
querydefs.go
queryfield.go
subquery.go
table.go
union.go

fix: dameng INET_ATON support

---

backends/dameng/dameng.go
backends/dameng/insert_test.go

fix: fatal if do insertOrUpdate on a table with autoincremental primary key

fix: fatal if do insertOrUpdate on a table with autoincremental primary key

---

backends.go
backends/clickhouse/functions.go
backends/dameng/functions.go
backends/mysql/functions.go
backends/sqlite/functions.go
backends_base.go
functions.go

feature: support cast type functions

feature: support cast type functions

---

functions.go

fix: support cast type functions round 2

fix: support cast type functions round 2

---

debug.go
reflect.go

fix: 避免浮点数损失精度

---

functions.go
query_test.go

fix: NewFunction add aggregate params

fix: NewFunction add aggregate params

---

table.go

fix: add more columns error

---

backends/clickhouse/column.go
backends/clickhouse/column_test.go
backends/clickhouse/columninfo.go

fix(clickhouse): decimal field

---

query_test.go
table.go
union.go

fix: label generate new field instance

fix: label generate new field instance

---

table.go

fix: sync table column index with lock

fix: sync table column index with lock

---

query.go

fix: subquery reference a copy of query

---

backends/dameng/dameng.go
backends/dameng/query_test.go

fix: dameng RegExp should use REGEXP_LIKE

fix: dameng RegExp should use REGEXP_LIKE

---

go.mod
go.sum

fix: upgrade sqlite3 to 1.14.19

fix: upgrade sqlite3 to 1.14.19

---

backends/clickhouse/clickhouse.go
backends/clickhouse/sync.go

fix: clickhouse sync table with order by changes

fix: clickhouse sync table with order by changes

---

delete_batch.go
filter.go
update_batch.go

fix: update batch convert value

fix: update batch convert value

---

backends/clickhouse/clickhouse.go

fix: clickhouse remove allow_nullable_key

---

backends/clickhouse/clickhouse.go

fix: clickhouse table

---

column.go

fix: convert compound column check is string value

---

backends/clickhouse/column_test.go
backends/dameng/column_test.go
backends/mysql/column_test.go
backends/sqlite/column_test.go
reflect.go
reflect_test.go

fix: convert to tristate revisited, ConvertFromValue should be idempotent.

fix: convert to tristate revisited
